import type { TestModel } from './test.model';

export const TEST_DATA: TestModel[] = [
  {
    sameNumber: 0,
    numberOnly: 1,
    optionalNumber: 1,
    nullableNumber: 1,
    numberAndString: 1,
    numberAndStringAndDate: 946_681_200_000, // 2000-01-01T00:00:00.000+01:00
    unknown: 1,
    nil: null,
    nestedObject: { content: '' },
  },
  {
    sameNumber: 0,
    numberOnly: 2,
    optionalNumber: undefined,
    nullableNumber: 2,
    numberAndString: '2',
    numberAndStringAndDate: '2010-01-01 00:00:00 GMT+0100',
    unknown: undefined,
    nil: undefined,
    nestedObject: { content: undefined },
  },
  {
    sameNumber: 0,
    numberOnly: 3,
    nullableNumber: null,
    numberAndString: 'invalid',
    numberAndStringAndDate: new Date('2020-01-01 00:00:00 GMT+0100'),
    unknown: {},
    nil: null,
    nestedObject: { content: {} },
  },
  {
    sameNumber: 0,
    numberOnly: 4,
    nullableNumber: null,
    numberAndString: 'invalid',
    numberAndStringAndDate: 'invalid',
    unknown: {},
    nil: null,
    nestedObject: { content: {} },
  },
  {
    sameNumber: 0,
    numberOnly: 5,
    nullableNumber: null,
    numberAndString: 'invalid',
    numberAndStringAndDate: new Date('invalid'),
    unknown: {},
    nil: null,
    nestedObject: { content: '1900/01/01 00:00:00 GMT+0100' },
  },
];
